- lib/network.js
Because the "onRequest" extension point could be side-stepped by an earlier "onRequest" extension point and cause downstream impacts, I changed to listen for the "request-internal" event because I think it happens earlier in the life cycle and can't be interrupted.
I also removed a few unnecessary `process.nextTick` calls. 
Closes #285
> Changed event for incoming request.

- lib/reporter.js
- test/reporter.js
Part one of new version. The idea is that when the reporters are started, they will receive the main good read stream and will be passed in this interface. That way, the reporters won't need to reference to any other modules. In the start function, the reports will create their own data pipeline and can use this one to do handle the event filtering. It also has two static methods on it as well in case the reporter doesn't want to implement itself as a stream.
Related to #292
> Created filter transform stream and tests.

- README.md
There was an error in the readme. It was using requestsEvent instead of responseEvent option key resulting in Error: Invalid monitorOptions options requestsEvent is not allowed
This is my first Fork & Pull ever. Let me know if I did anything incorrectly.
> Fix responseEvent option in readme

- lib/network.js
- test/network.js
* Added test
* Added fix (all credit to @chulkilee)
* Reference
* https://github.com/hapijs/hapi/issues/2344
* #298  #301 #285 #287 
If someone can help me squashing :innocent: (I've never done it and those commits don't show in my log :neutral_face: )
Thanks to @arb for the squashing help
> Fix: Cannot read property 'statusCodes' of undefined

- README.md
- lib/monitor.js
- package.json
- test/helper.js
- test/index.js
- test/monitor.js
> Updated to data stream and pipe method for transmitting data. 

- README.md
- lib/monitor.js
- lib/schema.js
- lib/utils.js
- package.json
- test/index.js
- test/monitor.js
> Added ability to filter globally

- lib/utils.js
- test/utils.js
Fixes #337. This handles the case when a payload is null (e.g., not posted with a `POST` method or masked by Hapi in case of `GET` method).
By the way: is it correct that Hapi passes null for the payload when a `GET` method is performed?
> applyFilter: handle empty payloads

- lib/utils.js
- test/utils.js
This is related to #285 and #303. It looks like this part of the code was forgotten in the fix, and we are still seeing errors in 5.1.2.
> fixes error when response is null

- lib/utils.js
- test/index.js
- test/monitor.js
- test/network.js
- test/utils.js
Fixes potential issue when replying with objects that have `.toString` methods directly attached to them such as Mongoose objects.
> Filter fix

- README.md
- lib/monitor.js
- lib/schema.js
- test/monitor.js
> Allows Good to start with no reporters.

- README.md
Fixes #360 - Added information to README to make clear that `server.connection` should be called prior to registering `Good`.
> Add NOTE to call  prior to registering

- README.md
- lib/utils.js
- test/utils.js
The GreatWreck event doesn't currently have the process pid or much documentation.
I added the pid to the event so it's consistent with the others and updated the ReadMe to cover the fields it exposes.
> Adds process pid to GreatWreck and updates documentation

- package.json
Wreck has released 6.0.0 - this PR updates the good wreck dependency otherwise you end up with multiple wreck versions in your node_modules folder and lose your wreck logs because of the whole singleton thing.
> Update wreck dependency

- README.md
- lib/monitor.js
- test/monitor.js
@arb 
As an alternative to https://github.com/hapijs/good/pull/375.
> Closes #357. Reporter name attribute used in errors

- lib/monitor.js
- lib/utils.js
Small fix as "this.constructor" fails within strict mode.
> Fixed this.constructor

- lib/index.js
- lib/monitor.js
- lib/schema.js
- test/index.js
- test/monitor.js
- Monitoring starts on registration
- Monitoring stops on onPostStop
- Ops starts on onPreStart
> Closes #407.

- lib/monitor.js
- package.json
- test/helper.js
- test/monitor.js
Closes #413. Push null to the data stream for EOF.
Closes #415. Remove "stop" event.
> End cleanup

- lib/index.js
- lib/monitor.js
- lib/schema.js
- package.json
- test/monitor.js
Also moved around validation logic to get more use from `Joi.default`
> Allow ops collecting to be disabled. Closes #411.

- API.md
- lib/utils.js
- test/monitor.js
This data is needed when trying to create a custom reporter for the apache combined log format.
> Add httpVersion to GreatResponse

- API.md
- README.md
- lib/utils.js
- test/monitor.js
Filter option now filters `query` also
use case: `access_token` in `query` land
> Improved filter option to also filter `query`

- README.md
I'm no longer maintainer of `good-loggly`.
> Update link to good-loggly

- lib/monitor.js
- lib/utils.js
- package.json
- test/monitor.js
- test/utils.js
As stated in the associated link, I'll be willing to add this back in when the eventing from `Wreck` is more predictable. In the current implementation, there are way too many variables to allow it to work properly 100% of the time.
> Removed wreck logging. Closes #402.

- API.md
- lib/utils.js
- test/monitor.js
- test/utils.js
I provide a pull request to extend the request event object with the root path.
With this path information, it is possible to provide a route specific event handling and interpreation. We use this information, to extend logging and monitoring informations (with good-bunyan and influx) with the hapi route.
> Support route path in request event object

- examples/censoring-with-white-out.md
- examples/filtering-with-white-out.md
- examples/good-squeeze-tips.md
- examples/log-to-console.md
- examples/log-to-file.md
- examples/log-to-http.md
Adds `examples` directory and examples for console, file, and http logging based on docs. Includes example of passing parameters to SafeJson (tested, works), log rotation (tested, works), and using white-out to censor data (untested).
> first examples

- README.md
The keys in the listed example could possibly be mistaken for reserved words.  Changed the keys to make it more obvious that the keys were defined by the user and to prevent possible confusion around creating multiple file reporters.  Added a link to the reporter interface section of the API as a quick reference.
> Changed keys used to identify reporters in example

- API.md
- lib/utils.js
to enable filtering with good-squeeze
> Add request route tags to response event

- API.md
- lib/monitor.js
- lib/schema.js
- test/fixtures/unnamed-reporter.js
- test/monitor.js
Hey,
In our project we stumbled upon a case where the simple string require wasn't enough because npm doing its deduplication work was bringing a different version of the module than we expected.
I don't want to break anyone's code so I kept the old way, which is imho unsafe, we can always remove it later.
I'm not sure the tests are enough but I'll wait for your guidance there.
> Support functions as modules

- README.md
Updated the current npm version shield in readme.md to point to the good package at npmjs.
> current version shield links to good @ npmjs

- API.md
- lib/utils.js
non breaking version of #531 . Adds a flag `responseSentTime` instead of breaking `responseTime` flag by changing definition. Docs updated.
> non breaking change adds responseSentTime. Closes #530

- lib/monitor.js
- test/monitor.js
Decided the simplest solution was just to _not create_ the reporter if no stream is provided.
See #534
> Don't create a reporter if no streams were provided. Addresses #534

- .gitignore
- API.md
- lib/monitor.js
- lib/schema.js
- lib/utils.js
- package.json
- test/monitor.js
- test/utils.js
Cleaned up event handling logic and just added a boolean to control whether events are reported on not. It was much easier and required far less code to keep a handler to all the added event listeners.
> Restored wreck logging. Closes #469.

- API.md
… unlike `uptime`, which is in seconds.
> Documentation: Clarify that event loop delay is in milliseconds

- lib/monitor.js
- test/monitor.js
> Add Wreck support for version 11 and above

- API.md
- CONTRIBUTING.md
- lib/monitor.js
- lib/utils.js
- package.json
- test/monitor.js
- test/utils.js
This is a draft fix for https://github.com/hapijs/good/issues/557 . In particular, this demonstrates what I have in mind there.  Happy to discuss this in more detail.
> Fix for 557: Provide request headers in various payload events

- .travis.yml
- API.md
- README.md
- lib/index.js
- lib/monitor.js
- lib/schema.js
- lib/utils.js
- package.json
- test/index.js
- test/monitor.js
- test/utils.js
Migrates to hapi 17, node 8 and async/await
I removed wreck support as wreck no longer issues the events needed
I am still trying to solve an issue where the tests emit ` MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit`
Any comments and help would be appreciated
> Migrate to hapi 17, node 8 and async/await closes #568

- API.md
- lib/utils.js
Hapi 15 docs:
`responded - request response timestamp (0 is not responded yet).` 
This will use the diff of responded to received as the response event `responseTime`. Fallback to `Date.now()` behavior when responded=0 or just in case any old Hapi versions don't set this.
No test added b/c I didn't see any similar testing of event flags. Glad to add one if needed.
> responseTime to use request responded. Closes #530

- lib/utils.js
- test/monitor.js
Since Hapi 17, request.id was moved to request.info.id.
Source: https://github.com/hapijs/hapi/issues/3658
> Moved request.id to request.info.id.
> request.id is now request.info.id since Hapi 17

- API.md
- lib/schema.js
- lib/utils.js
- test/monitor.js
Currently, there's no way to add response headers to response events (there's currently only request headers available). This PR adds that ability. My use-case is to be able to log content-length.
> Add support for logging response headers

- API.md
- lib/utils.js
- test/utils.js
Hapi has some logic that decides whether to include `error` or `data` on the request event object. It does this by simply checking if the log data is an instance of an Error object. This adds support for propagating that field properly. If you pass an error object right now as data, Good is completely unaware of it and simply drops it.
https://github.com/hapijs/hapi/blob/master/lib/core.js#L556-L558
> Add support for request event error field

- API.md
- lib/utils.js
- test/utils.js
As of Hapi17 calls to `server.log` that pass an error instances as the data will append the error to `event.error` and not `event.data`. As such this needs to be captured by good's `ServerLog` class.
> Add error property to server logs

- API.md
In the example code _Consuming the plugin config in the stream transform_ is the `event` property of data object incorrectly accessed as `data.eventName`
> Fix a typo in the example code

- API.md
- README.md
- examples/log-to-console.md
* **Problem:** Some packages in documentation don't have the updated `@hapi` scope
* **Solution:** Update the docs!
* **Testing:** n/a
> Update package scope in documentation

- lib/monitor.js
This fixes https://github.com/pnpm/pnpm/issues/1963
`@hapi/good` should search for plugins in the dependent project's
node_modules.
> fix: plugins should be searched for in the caller deps
