package.json
Removed Makefile. See https://github.com/hapijs/contrib/issues/14. Removed Moment. Closes #288
=> Remove Makefile. Remove moment

README.md, lib/monitor.js, lib/schema.js, lib/utils.js, test/monitor.js
- Renamed options
- Updated docs
- Updated tests
- Updated validation
Closes #299
=> Renamed options

README.md, lib/monitor.js, lib/schema.js, test/monitor.js
Added `extension` option to allow listening for additional hapi server events.
Closes #311 
Closes #286
=> Dynamic events

README.md
Added community powered reference to winston adapter
=> Added community powered reference to winston adapter

lib/monitor.js
=> Cleaned up stop function

lib/monitor.js, lib/network.js, lib/system.js, lib/utils.js, package.json, test/index.js, test/monitor.js, test/network.js, test/utils.js
=> Support request path and protocols

README.md, lib/network.js, test/index.js, test/network.js
=> Move Reporter Interface to end of README and explain it more.

package.json
Peg the minor version for now until the eslint file changes calm down.
=> Pegged lab version.

README.md
We made a custom reporter for the log service graylog. Consider adding to your README.md. Thanks!
=> Update README.md - good-graylog2 community plugin.

API.md, README.md
Moved API docs from README.md to API.md following the new [module documentation changes](https://github.com/hapijs/contrib/issues/49)
=> Added API documentation #378

lib/utils.js, test/monitor.js
- Attach route config good segment
- Attach request.plugins.good
=> Closes #397.

API.md
Fix for #427 
Took some small liberties with comments as I didn't fully understand what this each transform stream was doing when I first read through the docs. Hopefully this or something similar will help someone else.
=> update docs: make Reporter Interface example work

API.md
=> API typo - incomming -> incoming

test/monitor.js
=> Fixed broken test.

lib/monitor.js, lib/schema.js, lib/utils.js, test/monitor.js, test/utils.js
Update options to use `includes` which is an object that has `request` and `response` arrays.
=> Closes #336

lib/monitor.js, package.json, test/fixtures/reporters.js, test/monitor.js
Also switched to async because of 
> Use async for all your application needs.
from the "items" README and I didn't want to have two different async libs floating around.
=> Added stop to interface. Closes #437.

API.md
@arb Is this what you are looking for regarding docs for plugin configs?
=> Add docs for plugin configs in event payloads. Closes #472.

examples/censoring-with-white-out.md
Example has been validated [here](https://github.com/cilindrox/good-censor).
=> Remove untested warn

README.md
Added fall-through logic on no error in the example. Minor ES6-ified the code.
=> Made the README.md a little more ES6-ified

lib/monitor.js, test/monitor.js
=> Not enough feedback when error #498

API.md
A few typos and changed wording of the stream transform example in the docs. I thought it was worded in a way that made it seem like `Filtering` was something special when it's just a general example of how to use route and request level plugin configs.
=> update stream example in docs and other minors

package.json, test/monitor.js
=> Upgrade async

test/index.js, test/monitor.js
I updated tests as referenced in [#519](https://github.com/hapijs/good/issues/519).
The only thing to consider might be test/monitor.js@147 just because an assertion @139 requires it.
=> Test fixes. Closes #519

.travis.yml, lib/monitor.js, package.json, test/monitor.js
Fix extra console message. Update dependencies. Migrate wreck tests to newer
versions.
=> Test cleanup

examples/add-custom-transform-stream.md
This add an example that add custom transform stream #486.
=> Examples: Add custom transform stream
